-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 10:25:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `optica` ;

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`Provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`Provider` ;

CREATE TABLE IF NOT EXISTS `optica`.`Provider` (
  `idProvider` INT NOT NULL,
  `nom` VARCHAR(45) NULL COMMENT 'nom',
  `carrer` VARCHAR(45) NULL,
  `numero` INT NULL,
  `Pis` INT NULL,
  `Porta` INT NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` INT NULL,
  `pais` VARCHAR(45) NULL,
  `telef` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  PRIMARY KEY (`idProvider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Glasses_Desc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`Glasses_Desc` ;

CREATE TABLE IF NOT EXISTS `optica`.`Glasses_Desc` (
  `id_Glasses` INT NOT NULL,
  `model` ENUM('Round', 'Retro', 'Sun', 'Small', 'Fashion') NULL COMMENT ' La marca, la graduació de cadascun dels vidres, el tipus de muntura (flotant, pasta o metàl·lica), el color de la muntura, el color de cada vidre, el preu.',
  `marca` ENUM('Ray-Ban', 'Vogue', 'Vuarnet', 'Gafon', 'Pepes') NULL,
  `graduacio_ambes` VARCHAR(45) NULL,
  `tipus de montura` ENUM('Pasta', 'Ferro', 'Eco') NULL,
  `color_mont` ENUM('Marron', 'Claro', 'Violeta') NULL,
  `color_vidre` ENUM('Normal', 'Oscuro') NULL,
  `preu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Glasses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`Client` ;

CREATE TABLE IF NOT EXISTS `optica`.`Client` (
  `idl_cliente` INT NOT NULL,
  `nom` VARCHAR(45) NULL COMMENT 'El nom, l\'adreça postal, el telèfon, el correu electrònic, la data de registre.',
  `carrer` VARCHAR(45) NULL,
  `codi_postal` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `data_registre` DATE NULL,
  `client_recomend` TINYINT NULL,
  PRIMARY KEY (`idl_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Glasses_Desc_has_Provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`Glasses_Desc_has_Provider` ;

CREATE TABLE IF NOT EXISTS `optica`.`Glasses_Desc_has_Provider` (
  `Glasses_Desc_id_Glasses` INT NOT NULL,
  `Provider_idProvider` INT NOT NULL,
  PRIMARY KEY (`Glasses_Desc_id_Glasses`, `Provider_idProvider`),
  INDEX `fk_Glasses_Desc_has_Provider_Provider1_idx` (`Provider_idProvider` ASC) VISIBLE,
  INDEX `fk_Glasses_Desc_has_Provider_Glasses_Desc_idx` (`Glasses_Desc_id_Glasses` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Desc_has_Provider_Glasses_Desc`
    FOREIGN KEY (`Glasses_Desc_id_Glasses`)
    REFERENCES `optica`.`Glasses_Desc` (`id_Glasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Desc_has_Provider_Provider1`
    FOREIGN KEY (`Provider_idProvider`)
    REFERENCES `optica`.`Provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`Employee` ;

CREATE TABLE IF NOT EXISTS `optica`.`Employee` (
  `idEmployee` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`Orders` ;

CREATE TABLE IF NOT EXISTS `optica`.`Orders` (
  `idComandes` INT NOT NULL,
  `Glasses_Desc_id_Glasses` INT NOT NULL,
  `Client_idl_cliente` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `recomended` TINYINT NULL,
  `client_rec_id` INT NOT NULL,
  PRIMARY KEY (`idComandes`),
  INDEX `fk_Comandes_Glasses_Desc1_idx` (`Glasses_Desc_id_Glasses` ASC) VISIBLE,
  INDEX `fk_Comandes_Client1_idx` (`Client_idl_cliente` ASC) VISIBLE,
  INDEX `fk_Comandes_Employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comandes_Glasses_Desc1`
    FOREIGN KEY (`Glasses_Desc_id_Glasses`)
    REFERENCES `optica`.`Glasses_Desc` (`id_Glasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandes_Client1`
    FOREIGN KEY (`Client_idl_cliente`)
    REFERENCES `optica`.`Client` (`idl_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandes_Employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `optica`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandes_Client_Rec`
    FOREIGN KEY (`Client_idl_cliente`)
    REFERENCES `optica`.`Client` (`idl_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
